### ISSUE TITLE
Tagging releases in git

### ISSUE THREAD

**Issue by miguelaferreira** [jgoulah/x11vnc-cookbook#10]
Hi @jgoulah 

I've made a few PRs that you merged a while back. Meanwhile I've been using my own patched version of the cookbook.
Now I'm in the process of freezing dependencies on a cookbook that uses x11vnc.
So I go to the supermarket, I find the latest version and then I go to github to see if that version has the code I've submitted.
I usually do that by checking the commits on a given tag. Unfortunately there are no tags in the git repo.

May I suggest that we create tags for every release that goes into the supermarket?

I'm more that happy to help out and do that myself, if you want.

Cheers,

**Comment by jgoulah** [comment]
sure we can tag it starting from this version of code, suggestions on tag name?

**Comment by miguelaferreira** [comment]
Tag name is typically the release number.
If I would do it for this release it would be named something like: v0.0.6

**Comment by jgoulah** [comment]
done

**Comment by miguelaferreira** [comment]
Thanks!
