### ISSUE TITLE
Cookbook name and version are not in sync

### ISSUE THREAD

**Issue by miguelaferreira** [jgoulah/x11vnc-cookbook#8]
The repo contains a `metadata.json`file that is not in synch with the `metadata.rb`file, specifically in the name and version attributes.
This makes it impossible to use a `Berksfile` that points to this repo because `berks` will look at the `metadata.json` file and say the cookbook name is not `x11vnc` it is `x11vnc-cookbook`, and BTW it's version is not `0.0.4` it is `0.0.3`.

Suggestion: one way to avoid these issues is to not include the metadata.json in your git repo.

**Comment by jgoulah** [comment]
do you want to submit a PR to remove the metadata.json file and add it to .gitignore? that'd be fine by me

**Comment by jgoulah** [comment]
I removed and added to .gitignore

**Comment by miguelaferreira** [comment]
Just saw this now. Thanks
